FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

RUN mkdir -p /tmp/angular-dist \
    && BUILD_DIR="$(find /app/dist -name index.html -type f | head -n 1 | xargs dirname)" \
    && cp -r "$BUILD_DIR"/* /tmp/angular-dist/

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /tmp/angular-dist /usr/share/nginx/html

EXPOSE 80
