# Generated by Django 6.0.4 on 2026-04-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='projectmembership',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='projectrole',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='company',
            new_name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('organization', 'name')},
        ),
    ]
