# Generated by Django 6.0.4 on 2026-04-27 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
