# Generated by Django 6.0.4 on 2026-04-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='organization_icons/'),
        ),
    ]
