# Generated by Django 6.0.4 on 2026-04-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskgroup',
            unique_together=set(),
        ),
    ]
